(()=>{
  const script=document.currentScript;
  const room=(script?.dataset.room||'').trim();
  const targetSel=script?.dataset.target||'';
  const api=(script?.dataset.api||'').replace(/\/$/,'');
  if(!room||!targetSel||!api)return;
  const host=document.querySelector(targetSel);
  if(!host)return;

  const roomName=room==='roost'?'THE ROOST':'EAST BANK';
  const roomMark=room==='roost'?'ROOST CAM • MEMBERS CHAT':'CAMERA 01 • MEMBERS CHAT';

  const style=document.createElement('style');
  style.textContent=`
    .wchat-wrap{--wc-bg:#03100c;--wc-panel:#071713;--wc-panel2:#0b2118;--wc-line:rgba(255,255,255,.16);--wc-muted:#9db3a7;--wc-text:#f7fbf8;--wc-accent:#76d99a;--wc-warm:#f3cf7b;width:min(95vw,980px);margin:12px auto 0;font-family:Arial,sans-serif;color:var(--wc-text);position:relative;z-index:8}
    .wchat-wrap[data-room="roost"]{--wc-accent:#e7c36f;--wc-warm:#ffd77d}
    .wchat-toggle{display:flex;align-items:center;justify-content:center;gap:9px;margin:0 auto;padding:9px 15px;border-radius:999px;border:1px solid rgba(255,255,255,.2);background:linear-gradient(180deg,#142d22,#0b1d16);color:#fff;font-size:11px;font-weight:1000;letter-spacing:.11em;cursor:pointer;box-shadow:0 10px 24px #0006,inset 0 1px 0 #ffffff12;transition:transform .18s ease,background .18s ease,border-color .18s ease}
    .wchat-toggle:hover{background:linear-gradient(180deg,#193829,#0d241a);border-color:#ffffff42}.wchat-toggle:active{transform:scale(.98)}
    .wchat-toggle .wchat-bubble{width:23px;height:23px;border-radius:50%;display:grid;place-items:center;background:#ffffff10;border:1px solid #ffffff20;font-size:12px;box-shadow:inset 0 0 12px #0003}
    .wchat-panel{display:none;margin-top:12px;border:1px solid rgba(255,255,255,.2);border-radius:22px;background:linear-gradient(180deg,rgba(7,23,19,.98),rgba(2,10,7,.98));overflow:hidden;box-shadow:0 24px 60px #000a,inset 0 1px 0 #ffffff0f;backdrop-filter:blur(18px)}
    .wchat-panel.open{display:block;animation:wchatIn .18s ease-out}@keyframes wchatIn{from{opacity:0;transform:translateY(-4px)}to{opacity:1;transform:none}}
    .wchat-head{position:relative;display:flex;align-items:center;justify-content:space-between;gap:14px;padding:14px 16px;background:linear-gradient(135deg,#0c251b,#071711 65%,#101f18);border-bottom:1px solid var(--wc-line)}
    .wchat-head:after{content:"";position:absolute;left:0;right:0;bottom:-1px;height:1px;background:linear-gradient(90deg,transparent,var(--wc-accent),transparent);opacity:.45}
    .wchat-brand{display:flex;align-items:center;gap:11px;min-width:0}.wchat-brandmark{width:38px;height:38px;border-radius:13px;display:grid;place-items:center;background:radial-gradient(circle at 35% 30%,#ffffff16,transparent 45%),#10291e;border:1px solid #ffffff24;box-shadow:0 8px 20px #0006;font-size:17px}
    .wchat-title{min-width:0}.wchat-title strong{display:block;font-size:14px;line-height:1.1;letter-spacing:.08em}.wchat-title small{display:block;margin-top:4px;color:var(--wc-muted);font-size:9px;letter-spacing:.16em;font-weight:900}
    .wchat-live{display:flex;align-items:center;gap:6px;white-space:nowrap;padding:6px 9px;border-radius:999px;background:#ffffff08;border:1px solid #ffffff15;color:#dce9e1;font-size:9px;font-weight:900;letter-spacing:.12em}.wchat-live i{width:7px;height:7px;border-radius:50%;background:var(--wc-accent);box-shadow:0 0 12px var(--wc-accent)}
    .wchat-body{padding:14px}.wchat-auth{display:grid;gap:10px;max-width:560px;margin:2px auto}.wchat-intro{text-align:center;padding:4px 10px 2px}.wchat-intro b{display:block;font-size:17px;letter-spacing:.02em}.wchat-intro span{display:block;margin-top:5px;color:var(--wc-muted);font-size:11px;line-height:1.45}
    .wchat-tabs{display:grid;grid-template-columns:1fr 1fr;gap:6px;padding:4px;border-radius:13px;background:#020b08;border:1px solid #ffffff11}.wchat-tab{padding:9px 8px;border-radius:10px;border:0;background:transparent;color:#9fb3a7;font-weight:900;font-size:10px;letter-spacing:.08em;cursor:pointer}.wchat-tab.active{background:linear-gradient(180deg,#173a29,#10281d);color:#fff;box-shadow:0 4px 12px #0005,inset 0 1px 0 #ffffff10}
    .wchat-fieldwrap{position:relative}.wchat-fieldwrap span{position:absolute;left:12px;top:50%;transform:translateY(-50%);opacity:.65;font-size:12px;pointer-events:none}.wchat-input{width:100%;padding:12px 12px;border-radius:12px;border:1px solid #ffffff20;background:#04110d;color:#fff;outline:none;font-size:13px;box-shadow:inset 0 1px 8px #0005;transition:border-color .16s ease,box-shadow .16s ease}.wchat-fieldwrap .wchat-input{padding-left:34px}.wchat-input::placeholder{color:#6f8378}.wchat-input:focus{border-color:color-mix(in srgb,var(--wc-accent) 62%,white 0%);box-shadow:0 0 0 3px rgba(118,217,154,.09),inset 0 1px 8px #0004}
    .wchat-btn{padding:11px 13px;border:1px solid #ffffff12;border-radius:12px;background:linear-gradient(180deg,#2f724d,#245b3d);color:#fff;font-weight:1000;font-size:11px;letter-spacing:.08em;cursor:pointer;box-shadow:0 8px 18px #0005,inset 0 1px 0 #ffffff15}.wchat-wrap[data-room="roost"] .wchat-btn{background:linear-gradient(180deg,#8a6b2f,#6e5425)}.wchat-btn:disabled{opacity:.55;cursor:wait}
    .wchat-note{padding:8px 10px;border-radius:10px;background:#ffffff05;border:1px solid #ffffff0e;font-size:10px;color:#8ea298;line-height:1.45;text-align:center}.wchat-error{font-size:11px;color:#ffb7b7;min-height:15px;text-align:center;font-weight:700}.wchat-room{display:none}.wchat-room.show{display:block}
    .wchat-userbar{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:10px;padding:9px 11px;border-radius:12px;background:#ffffff05;border:1px solid #ffffff12;font-size:10px;color:#bcd0c4}.wchat-userbar b{color:#fff}.wchat-adminbadge{display:inline-flex;margin-left:5px;padding:3px 6px;border-radius:999px;background:#ffd77d18;border:1px solid #ffd77d33;color:#ffd77d;font-size:8px;font-weight:1000;letter-spacing:.08em}.wchat-logout{border:0;background:none;color:var(--wc-warm);font-weight:900;font-size:9px;letter-spacing:.08em;cursor:pointer}
    .wchat-msgs{height:300px;overflow:auto;padding:10px;border-radius:15px;background:linear-gradient(180deg,#020906,#030d09);border:1px solid #ffffff14;box-shadow:inset 0 6px 20px #0005;scrollbar-width:thin;scrollbar-color:#284637 #07100c}
    .wchat-msg{position:relative;padding:10px 10px 9px 46px;margin:0 0 7px;border-radius:13px;background:#ffffff04;border:1px solid #ffffff0b;font-size:13px;line-height:1.35}.wchat-msg:last-child{margin-bottom:0}.wchat-msg:hover{background:#ffffff06;border-color:#ffffff12}
    .wchat-avatar{position:absolute;left:9px;top:9px;width:28px;height:28px;border-radius:10px;display:grid;place-items:center;background:linear-gradient(180deg,#183b2a,#10271d);border:1px solid #ffffff18;color:#c9f0d8;font-size:11px;font-weight:1000;box-shadow:0 5px 12px #0004}.wchat-avatar.admin{background:linear-gradient(180deg,#5f4b22,#3f3218);color:#ffe6a3}.wchat-name{font-weight:1000;color:#9ee0b7}.wchat-name.admin{color:#ffd87c}.wchat-time{margin-left:7px;font-size:9px;color:#6f8378}.wchat-text{display:block;margin-top:3px;color:#eef4f0;word-break:break-word}
    .wchat-admin{display:flex;gap:5px;margin-top:7px;flex-wrap:wrap}.wchat-mini{border:1px solid #ffffff18;background:#0d1f17;color:#d9e4dd;border-radius:8px;padding:5px 7px;font-size:8px;font-weight:900;letter-spacing:.05em;cursor:pointer}.wchat-mini:hover{background:#173124}.wchat-mini[data-act="delete"]{color:#ffcccc}.wchat-mini[data-act="all"]{color:#ffd3a5}
    .wchat-send{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:10px;padding:9px;border-radius:14px;background:#ffffff04;border:1px solid #ffffff0f}.wchat-send .wchat-input{border:0;background:#020a07;box-shadow:none}.wchat-send .wchat-btn{min-width:74px;padding-inline:14px}.wchat-status{margin-top:7px;padding-left:4px;font-size:10px;color:#91a69a;min-height:13px}
    @media(max-width:620px){.wchat-wrap{width:100%}.wchat-panel{border-radius:18px}.wchat-head{padding:12px}.wchat-brandmark{width:34px;height:34px;border-radius:11px}.wchat-title strong{font-size:12px}.wchat-live{font-size:8px}.wchat-body{padding:10px}.wchat-msgs{height:270px}.wchat-send{grid-template-columns:1fr auto;padding:7px}.wchat-send .wchat-btn{min-width:64px}.wchat-msg{padding-left:43px}.wchat-toggle{font-size:10px}}
  `;
  document.head.appendChild(style);

  const wrap=document.createElement('div');
  wrap.className='wchat-wrap';
  wrap.dataset.room=room;
  wrap.innerHTML=`<button class="wchat-toggle" type="button"><span class="wchat-bubble">💬</span><span>OPEN CHAT</span></button><section class="wchat-panel" aria-live="polite"><div class="wchat-head"><div class="wchat-brand"><div class="wchat-brandmark">${room==='roost'?'🐓':'◉'}</div><div class="wchat-title"><strong>${roomName} CHAT</strong><small>${roomMark}</small></div></div><div class="wchat-live"><i></i> WVLRP LIVE</div></div><div class="wchat-body"><div class="wchat-auth"><div class="wchat-intro"><b>Join the conversation</b><span>WVLRP member chat is private to signed-in members. Create an account once and use it across our live camera rooms.</span></div><div class="wchat-tabs"><button class="wchat-tab active" data-mode="login">SIGN IN</button><button class="wchat-tab" data-mode="register">CREATE ACCOUNT</button></div><div class="wchat-fieldwrap"><span>👤</span><input class="wchat-input" data-field="username" maxlength="24" placeholder="Username"></div><div class="wchat-fieldwrap"><span>🔒</span><input class="wchat-input" data-field="password" type="password" maxlength="128" placeholder="Password"></div><button class="wchat-btn" data-action="auth">SIGN IN TO CHAT</button><div class="wchat-error"></div><div class="wchat-note">Be decent to each other. WVLRP admins can remove messages or block disruptive accounts.</div></div><div class="wchat-room"><div class="wchat-userbar"><span></span><button class="wchat-logout">LOG OUT</button></div><div class="wchat-msgs"></div><form class="wchat-send"><input class="wchat-input" maxlength="500" placeholder="Say something…" autocomplete="off"><button class="wchat-btn" type="submit">SEND</button></form><div class="wchat-status"></div></div></div></section>`;
  host.appendChild(wrap);

  const toggle=wrap.querySelector('.wchat-toggle'),panel=wrap.querySelector('.wchat-panel'),auth=wrap.querySelector('.wchat-auth'),roomBox=wrap.querySelector('.wchat-room'),tabs=[...wrap.querySelectorAll('.wchat-tab')],userField=wrap.querySelector('[data-field=username]'),passField=wrap.querySelector('[data-field=password]'),authBtn=wrap.querySelector('[data-action=auth]'),err=wrap.querySelector('.wchat-error'),userbar=wrap.querySelector('.wchat-userbar span'),logout=wrap.querySelector('.wchat-logout'),msgs=wrap.querySelector('.wchat-msgs'),sendForm=wrap.querySelector('.wchat-send'),sendInput=sendForm.querySelector('input'),status=wrap.querySelector('.wchat-status');
  let mode='login',opened=false,started=false,timer=null,lastId=0,user=null;
  const tokenKey='wvlrpChatToken';
  const getToken=()=>localStorage.getItem(tokenKey)||'';
  const headers=()=>({'Content-Type':'application/json','Authorization':'Bearer '+getToken()});
  const safe=s=>(s??'').toString().replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const when=s=>{try{return new Date(s).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}catch{return ''}};
  const initial=s=>(s||'?').trim().charAt(0).toUpperCase()||'?';
  async function req(path,opt={}){const r=await fetch(api+path,opt);let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.detail||'Request failed');return j}
  function setMode(m){mode=m;tabs.forEach(t=>t.classList.toggle('active',t.dataset.mode===m));authBtn.textContent=m==='login'?'SIGN IN TO CHAT':'CREATE WVLRP ACCOUNT';err.textContent=''}
  tabs.forEach(t=>t.onclick=()=>setMode(t.dataset.mode));
  function stop(){if(timer){clearInterval(timer);timer=null}}
  function showAuth(message=''){stop();user=null;auth.style.display='grid';roomBox.classList.remove('show');err.textContent=message}
  function showRoom(){auth.style.display='none';roomBox.classList.add('show');userbar.innerHTML=`SIGNED IN AS <b>${safe(user.username)}</b>${user.role==='admin'?'<span class="wchat-adminbadge">ADMIN</span>':''}`;load(true);stop();timer=setInterval(()=>load(false),3000)}
  async function who(){const token=getToken();if(!token)return showAuth();try{user=await req('/api/me',{headers:headers()});showRoom()}catch{localStorage.removeItem(tokenKey);showAuth()}}
  authBtn.onclick=async()=>{err.textContent='';const username=userField.value.trim(),password=passField.value;if(!username||!password){err.textContent='Enter a username and password.';return}authBtn.disabled=true;try{const j=await req('/api/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});localStorage.setItem(tokenKey,j.token);user=j.user;passField.value='';showRoom();window.WVLRP_AUTH?.refresh?.()}catch(e){err.textContent=e.message}finally{authBtn.disabled=false}};
  logout.onclick=()=>{localStorage.removeItem(tokenKey);lastId=0;msgs.innerHTML='';showAuth();window.WVLRP_AUTH?.refresh?.()};
  function render(m){const el=document.createElement('div');el.className='wchat-msg';el.dataset.id=m.id;let admin='';if(user?.role==='admin'&&m.user_id!==user.id){admin=`<div class="wchat-admin"><button class="wchat-mini" data-act="delete">DELETE MESSAGE</button><button class="wchat-mini" data-act="room">BLOCK THIS ROOM</button><button class="wchat-mini" data-act="all">BAN ALL CHAT</button></div>`}el.innerHTML=`<span class="wchat-avatar ${m.role==='admin'?'admin':''}">${safe(initial(m.username))}</span><span class="wchat-name ${m.role==='admin'?'admin':''}">${safe(m.username)}${m.role==='admin'?' ★':''}</span><span class="wchat-time">${safe(when(m.created_at))}</span><span class="wchat-text">${safe(m.body)}</span>${admin}`;if(admin){el.querySelector('[data-act=delete]').onclick=()=>adminAction('delete',m,el);el.querySelector('[data-act=room]').onclick=()=>adminAction('room',m,el);el.querySelector('[data-act=all]').onclick=()=>adminAction('all',m,el)}msgs.appendChild(el);lastId=Math.max(lastId,Number(m.id)||0)}
  async function adminAction(action,m,el){try{if(action==='delete'){await req('/api/admin/messages/'+m.id,{method:'DELETE',headers:headers()});el.remove();return}const roomVal=action==='room'?room:null;const reason=prompt(action==='room'?'Reason for blocking this member from this room?':'Reason for banning this member from all WVLRP chat?')||'';await req('/api/admin/ban',{method:'POST',headers:headers(),body:JSON.stringify({user_id:m.user_id,room:roomVal,reason})});status.textContent=action==='room'?m.username+' blocked from this room.':m.username+' banned from WVLRP chat.'}catch(e){status.textContent=e.message}}
  async function load(initialLoad){if(!user)return;try{const path='/api/messages?room='+encodeURIComponent(room)+(initialLoad?'':'&after='+lastId);const j=await req(path,{headers:headers()});if(initialLoad){msgs.innerHTML='';lastId=0}const wasNear=msgs.scrollHeight-msgs.scrollTop-msgs.clientHeight<70;(j.messages||[]).forEach(render);if(initialLoad||wasNear)msgs.scrollTop=msgs.scrollHeight;status.textContent=''}catch(e){status.textContent=e.message;if(/login|account|blocked/i.test(e.message))stop()}}
  sendForm.onsubmit=async e=>{e.preventDefault();const body=sendInput.value.trim();if(!body)return;sendInput.disabled=true;try{const m=await req('/api/messages',{method:'POST',headers:headers(),body:JSON.stringify({room,body})});sendInput.value='';render(m);msgs.scrollTop=msgs.scrollHeight;status.textContent=''}catch(e2){status.textContent=e2.message}finally{sendInput.disabled=false;sendInput.focus()}};
  window.addEventListener('wvlrp-auth-change',e=>{const next=e.detail||null;if(next){user=next;if(opened)showRoom()}else{lastId=0;msgs.innerHTML='';showAuth()}});
  toggle.onclick=()=>{opened=!opened;panel.classList.toggle('open',opened);toggle.querySelector('span:last-child').textContent=opened?'CLOSE CHAT':'OPEN CHAT';if(opened&&!started){started=true;who()}if(!opened)stop();else if(user&&!timer){timer=setInterval(()=>load(false),3000)}};
})();
