(()=>{
  const script=document.currentScript;
  const room=(script?.dataset.room||'').trim();
  const targetSel=script?.dataset.target||'';
  const api=(script?.dataset.api||'').replace(/\/$/,'');
  if(!room||!targetSel||!api)return;
  const host=document.querySelector(targetSel);
  if(!host)return;

  const style=document.createElement('style');
  style.textContent=`
    .wchat-wrap{width:min(95vw,980px);margin:10px auto 0;font-family:Arial,sans-serif;color:#fff}
    .wchat-toggle{display:flex;align-items:center;justify-content:center;gap:8px;margin:0 auto;padding:9px 14px;border-radius:999px;border:1px solid #ffffff2d;background:#10271d;color:#fff;font-size:12px;font-weight:900;letter-spacing:.08em;cursor:pointer;box-shadow:0 8px 20px #0005}
    .wchat-panel{display:none;margin-top:10px;border:1px solid #ffffff2a;border-radius:16px;background:#04100c;overflow:hidden;box-shadow:0 16px 34px #0008}
    .wchat-panel.open{display:block}.wchat-head{display:flex;align-items:center;justify-content:space-between;padding:10px 12px;background:#0a1d15;border-bottom:1px solid #ffffff1e}.wchat-head strong{font-size:13px;letter-spacing:.08em}.wchat-head small{color:#9fb2a7}.wchat-body{padding:12px}.wchat-auth{display:grid;gap:8px}.wchat-tabs{display:flex;gap:6px}.wchat-tab{flex:1;padding:8px;border-radius:9px;border:1px solid #ffffff24;background:#0d2118;color:#fff;font-weight:800}.wchat-tab.active{background:#1a3c2b}.wchat-input{width:100%;padding:10px 11px;border-radius:10px;border:1px solid #ffffff28;background:#07150f;color:#fff;outline:none}.wchat-btn{padding:10px 12px;border:0;border-radius:10px;background:#2d6d49;color:#fff;font-weight:900;cursor:pointer}.wchat-note{font-size:11px;color:#9fb2a7;line-height:1.4}.wchat-error{font-size:11px;color:#ffb0b0;min-height:15px}.wchat-room{display:none}.wchat-room.show{display:block}.wchat-userbar{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:8px;font-size:11px;color:#bcd0c4}.wchat-logout{border:0;background:none;color:#ffd693;font-weight:800;cursor:pointer}.wchat-msgs{height:260px;overflow:auto;padding:8px;border-radius:12px;background:#020906;border:1px solid #ffffff1c}.wchat-msg{padding:7px 8px;border-bottom:1px solid #ffffff12;font-size:13px;line-height:1.35}.wchat-msg:last-child{border-bottom:0}.wchat-name{font-weight:900;color:#9ee0b7}.wchat-name.admin{color:#ffd87c}.wchat-time{margin-left:6px;font-size:10px;color:#72877b}.wchat-text{display:block;margin-top:2px;word-break:break-word}.wchat-admin{display:flex;gap:5px;margin-top:5px;flex-wrap:wrap}.wchat-mini{border:1px solid #ffffff24;background:#14271f;color:#fff;border-radius:7px;padding:4px 7px;font-size:9px;font-weight:800;cursor:pointer}.wchat-send{display:flex;gap:7px;margin-top:8px}.wchat-send .wchat-input{flex:1}.wchat-send .wchat-btn{padding-inline:15px}.wchat-status{margin-top:6px;font-size:10px;color:#91a69a;min-height:13px}@media(max-width:620px){.wchat-msgs{height:230px}.wchat-wrap{width:100%}.wchat-panel{border-radius:14px}.wchat-send{align-items:stretch}.wchat-btn{font-size:12px}}
  `;
  document.head.appendChild(style);

  const wrap=document.createElement('div');
  wrap.className='wchat-wrap';
  wrap.innerHTML=`<button class="wchat-toggle" type="button">💬 <span>CHAT</span></button><section class="wchat-panel" aria-live="polite"><div class="wchat-head"><strong>${room==='roost'?'THE ROOST':'EAST BANK'} CHAT</strong><small>WVLRP MEMBERS</small></div><div class="wchat-body"><div class="wchat-auth"><div class="wchat-tabs"><button class="wchat-tab active" data-mode="login">SIGN IN</button><button class="wchat-tab" data-mode="register">REGISTER</button></div><input class="wchat-input" data-field="username" maxlength="24" placeholder="Username"><input class="wchat-input" data-field="password" type="password" maxlength="128" placeholder="Password"><button class="wchat-btn" data-action="auth">SIGN IN</button><div class="wchat-error"></div><div class="wchat-note">A WVLRP account is required to enter the chat. Usernames are public; passwords are private.</div></div><div class="wchat-room"><div class="wchat-userbar"><span></span><button class="wchat-logout">LOG OUT</button></div><div class="wchat-msgs"></div><form class="wchat-send"><input class="wchat-input" maxlength="500" placeholder="Write a message…" autocomplete="off"><button class="wchat-btn" type="submit">SEND</button></form><div class="wchat-status"></div></div></div></section>`;
  host.appendChild(wrap);

  const toggle=wrap.querySelector('.wchat-toggle'),panel=wrap.querySelector('.wchat-panel'),auth=wrap.querySelector('.wchat-auth'),roomBox=wrap.querySelector('.wchat-room'),tabs=[...wrap.querySelectorAll('.wchat-tab')],userField=wrap.querySelector('[data-field=username]'),passField=wrap.querySelector('[data-field=password]'),authBtn=wrap.querySelector('[data-action=auth]'),err=wrap.querySelector('.wchat-error'),userbar=wrap.querySelector('.wchat-userbar span'),logout=wrap.querySelector('.wchat-logout'),msgs=wrap.querySelector('.wchat-msgs'),sendForm=wrap.querySelector('.wchat-send'),sendInput=sendForm.querySelector('input'),status=wrap.querySelector('.wchat-status');
  let mode='login',opened=false,started=false,timer=null,lastId=0,user=null;
  const tokenKey='wvlrpChatToken';
  const getToken=()=>localStorage.getItem(tokenKey)||'';
  const headers=()=>({'Content-Type':'application/json','Authorization':'Bearer '+getToken()});
  const safe=s=>(s??'').toString().replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const when=s=>{try{return new Date(s).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}catch{return ''}};
  async function req(path,opt={}){const r=await fetch(api+path,opt);let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.detail||'Request failed');return j}
  function setMode(m){mode=m;tabs.forEach(t=>t.classList.toggle('active',t.dataset.mode===m));authBtn.textContent=m==='login'?'SIGN IN':'CREATE ACCOUNT';err.textContent=''}
  tabs.forEach(t=>t.onclick=()=>setMode(t.dataset.mode));
  function stop(){if(timer){clearInterval(timer);timer=null}}
  function showAuth(message=''){stop();user=null;auth.style.display='grid';roomBox.classList.remove('show');err.textContent=message}
  function showRoom(){auth.style.display='none';roomBox.classList.add('show');userbar.innerHTML=`SIGNED IN AS <b>${safe(user.username)}</b>${user.role==='admin'?' • ADMIN':''}`;load(true);stop();timer=setInterval(()=>load(false),3000)}
  async function who(){const token=getToken();if(!token)return showAuth();try{user=await req('/api/me',{headers:headers()});showRoom()}catch{localStorage.removeItem(tokenKey);showAuth()}}
  authBtn.onclick=async()=>{err.textContent='';const username=userField.value.trim(),password=passField.value;if(!username||!password){err.textContent='Enter a username and password.';return}authBtn.disabled=true;try{const j=await req('/api/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});localStorage.setItem(tokenKey,j.token);user=j.user;passField.value='';showRoom()}catch(e){err.textContent=e.message}finally{authBtn.disabled=false}};
  logout.onclick=()=>{localStorage.removeItem(tokenKey);lastId=0;msgs.innerHTML='';showAuth()};
  function render(m){const el=document.createElement('div');el.className='wchat-msg';el.dataset.id=m.id;let admin='';if(user?.role==='admin'&&m.user_id!==user.id){admin=`<div class="wchat-admin"><button class="wchat-mini" data-act="delete">DELETE</button><button class="wchat-mini" data-act="room">BLOCK ROOM</button><button class="wchat-mini" data-act="all">BAN ALL CHAT</button></div>`}el.innerHTML=`<span class="wchat-name ${m.role==='admin'?'admin':''}">${safe(m.username)}${m.role==='admin'?' ★':''}</span><span class="wchat-time">${safe(when(m.created_at))}</span><span class="wchat-text">${safe(m.body)}</span>${admin}`;if(admin){el.querySelector('[data-act=delete]').onclick=()=>adminAction('delete',m,el);el.querySelector('[data-act=room]').onclick=()=>adminAction('room',m,el);el.querySelector('[data-act=all]').onclick=()=>adminAction('all',m,el)}msgs.appendChild(el);lastId=Math.max(lastId,Number(m.id)||0)}
  async function adminAction(action,m,el){try{if(action==='delete'){await req('/api/admin/messages/'+m.id,{method:'DELETE',headers:headers()});el.remove();return}const roomVal=action==='room'?room:null;const reason=prompt(action==='room'?'Reason for blocking this member from this room?':'Reason for banning this member from all WVLRP chat?')||'';await req('/api/admin/ban',{method:'POST',headers:headers(),body:JSON.stringify({user_id:m.user_id,room:roomVal,reason})});status.textContent=action==='room'?m.username+' blocked from this room.':m.username+' banned from WVLRP chat.'}catch(e){status.textContent=e.message}}
  async function load(initial){if(!user)return;try{const path='/api/messages?room='+encodeURIComponent(room)+(initial?'':'&after='+lastId);const j=await req(path,{headers:headers()});if(initial){msgs.innerHTML='';lastId=0}const wasNear=msgs.scrollHeight-msgs.scrollTop-msgs.clientHeight<70;(j.messages||[]).forEach(render);if(initial||wasNear)msgs.scrollTop=msgs.scrollHeight;status.textContent=''}catch(e){status.textContent=e.message;if(/login|account|blocked/i.test(e.message))stop()}}
  sendForm.onsubmit=async e=>{e.preventDefault();const body=sendInput.value.trim();if(!body)return;sendInput.disabled=true;try{const m=await req('/api/messages',{method:'POST',headers:headers(),body:JSON.stringify({room,body})});sendInput.value='';render(m);msgs.scrollTop=msgs.scrollHeight;status.textContent=''}catch(e2){status.textContent=e2.message}finally{sendInput.disabled=false;sendInput.focus()}};
  toggle.onclick=()=>{opened=!opened;panel.classList.toggle('open',opened);toggle.querySelector('span').textContent=opened?'CLOSE CHAT':'CHAT';if(opened&&!started){started=true;who()}if(!opened)stop();else if(user&&!timer){timer=setInterval(()=>load(false),3000)}};
})();
