(()=>{const cs=[...document.scripts].find(s=>/chat-widget\.js/.test(s.src)&&s.dataset.room);if(!cs)return;const room=cs.dataset.room,api=(cs.dataset.api||'').replace(/\/$/,'');const host=document.querySelector(cs.dataset.target||'');if(!room||!api||!host)return;
const s=document.createElement('style');s.textContent='.hatch{width:min(95vw,980px);margin:10px auto;color:#eef7f0;font-family:Arial,sans-serif}.hatch button{border:1px solid #ffffff22;background:#10291e;color:#fff;border-radius:12px;padding:10px 12px;font-weight:900}.hatch-card{display:none;margin-top:8px;padding:12px;border:1px solid #ffffff22;border-radius:18px;background:#06130f}.hatch-card.open{display:block}.hatch-row{display:flex;gap:7px;flex-wrap:wrap}.hatch-talk{font-size:17px;min-width:52px}.hatch-input{box-sizing:border-box;width:100%;margin:8px 0;padding:12px;border-radius:12px;border:1px solid #ffffff22;background:#020a07;color:white}.hatch-out{min-height:44px;margin-top:9px;padding:10px;border-radius:12px;background:#ffffff08;line-height:1.4}.hatch-small{font-size:10px;color:#9fb3a7;margin-top:7px}.hatch-badge{color:#ffd77d;font-weight:900}';document.head.appendChild(s);
const w=document.createElement('div');w.className='hatch';w.innerHTML='<button class="hatch-open">🌿 ASK HATCH</button><div class="hatch-card"><b>HATCH • WVLRP WILDLIFE RANGER</b><div class="hatch-small">Wildlife help, camera-audio questions, sightings, games, and Hatch-controlled camera requests.</div><input class="hatch-input" maxlength="500" placeholder="Hey Hatch, what animal makes that sound?"><div class="hatch-row"><button class="hatch-send">ASK</button><button class="hatch-talk">🎙️</button><button class="hatch-see">📸 SIGHTING</button><button class="hatch-game">🦝 QUIZ</button><button class="hatch-move">🎥 ASK HATCH TO MOVE CAMERA</button></div><div class="hatch-out">Hatch is ready.</div><div class="hatch-small">Camera requests never give viewers PTZ controls. Hatch handles the move and the camera returns to its normal position.</div></div>';host.appendChild(w);
const card=w.querySelector('.hatch-card'),input=w.querySelector('.hatch-input'),out=w.querySelector('.hatch-out');const token=()=>localStorage.getItem('wvlrpChatToken')||'';async function req(p,b){if(!token())throw Error('Sign in to WVLRP chat first.');const r=await fetch(api+p,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token()},body:JSON.stringify(b)});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.detail||'Hatch could not complete that.');return j}
w.querySelector('.hatch-open').onclick=()=>card.classList.toggle('open');async function ask(t){out.textContent='Hatch is checking…';try{const j=await req('/api/hatch/ask',{room,text:t,audio_seconds:/sound|hear/i.test(t)?15:0});out.textContent=j.reply}catch(e){out.textContent=e.message}}
w.querySelector('.hatch-send').onclick=()=>{const t=input.value.trim();if(t)ask(t)};input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();w.querySelector('.hatch-send').click()}};
w.querySelector('.hatch-game').onclick=()=>ask('Hatch, give me a wildlife quiz');
w.querySelector('.hatch-see').onclick=async()=>{const note=prompt('What did you see? You can edit this before sending.');if(!note)return;out.textContent='Saving sighting…';try{const j=await req('/api/hatch/sighting',{room,label:'Viewer sighting',note});out.textContent=j.message}catch(e){out.textContent=e.message}};
w.querySelector('.hatch-move').onclick=async()=>{const q=prompt('What would you like Hatch to look toward? Hatch keeps control of the camera.');if(!q)return;out.textContent='Sending camera request…';try{const j=await req('/api/hatch/camera-request',{room,request:q,duration_seconds:60});out.textContent=j.message}catch(e){out.textContent=e.message}};
const mic=w.querySelector('.hatch-talk');const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){mic.disabled=true;mic.title='Voice input is not supported in this browser'}else{mic.onclick=()=>{const r=new SR();r.lang='en-US';r.interimResults=false;r.onresult=e=>{input.value=e.results[0][0].transcript;input.focus()};r.onerror=()=>out.textContent='Voice input did not catch that. Try again.';r.start()}};
})();