(()=>{'use strict';
const KEY='wvlrpFieldCases2', read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return {}}};
const s=Object.assign({accepted:[],clues:[],done:[],firstVisit:new Date().toISOString(),watch:0,nightDate:'',daySearch:0},read());
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(s))}catch{}};
const add=(key,v)=>{if(!s[key].includes(v)){s[key].push(v);save()}};
const has=(key,v)=>s[key].includes(v);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stamp=()=>{let a=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date());let p=Object.fromEntries(a.map(x=>[x.type,x.value]));return{date:p.year+'-'+p.month+'-'+p.day,night:Number(p.hour)>=20||Number(p.hour)<6}};
const cases=[
['nuts','Where Have the Nuts Gone?','A squirrel has returned to an emptied winter store. Follow signs near the nut trees.',['shells'],'Squirrel tracker stamp','The cracked shells provide a useful trail, though the ranger cannot yet identify who took the cache.'],
['honey','Honey, I Miss You','The honeybees have lost their honey. Look for signs before blaming any animal.',['wax'],'Pollinator observer stamp','Fragments of old comb have been logged. They are evidence of disturbance, not proof of the culprit.'],
['knife','The Missing Pocketknife','A walker misplaced a little pocketknife while whittling a stick along a woodland trail.',['shavings'],'Trail finder stamp','A whittled stick narrows the search area. The owner has a proper lead.'],
['ranger','A Worried Ranger','Things have gone missing while I was out maintaining camera systems. Review the first three reports before opening this one.',['tag'],'Ranger’s field badge','The missing maintenance tag has been logged and placed with the inventory.'],
['puppy','A Missing Companion','A visitor quietly reported a missing little companion. There are no trail directions or clues at the station.',['toy','owl','daytrail'],'Quiet investigator stamp','The chewed toy and small tracks are recorded. The animal has not been declared found.'],
['bear','The Strange Shadow','An old caller described a tall shape and was sent to the Kentucky Live Research Project for Bigfoot questions. What does the ground really say?',['print'],'Careful observer stamp','The print is consistent with a bear. The ranger has amended the report without making a sensational claim.'],
['marker','The Ranger’s Trail Marker','A weather-beaten trail marker came loose. See whether the trail still bears signs of it.',['markerfind'],'Trail steward stamp','The fallen tag has been reported for safe replacement.']
].map(([id,name,intro,clues,reward,finish])=>({id,name,intro,clues,reward,finish}));
const byId=Object.fromEntries(cases.map(c=>[c.id,c]));
const piles=[
{title:'Woodland reports',ids:['nuts','honey','knife','ranger']},
{title:'Visitor requests',ids:['puppy']},
{title:'The old telephone file',ids:['bear']},
{title:'Maintenance reports',ids:['marker']},
{title:'Visitor letters',ids:[],text:'Letters and photographs are being archived for future cases.',notes:['A postcard with no return address','A note about a strange light on the hill','A request to help identify a bird','An unsigned thank-you from a visitor']},
{title:'Field specimens',ids:[],text:'The specimens will open more investigations when the field notes are ready.',notes:['Pressed pawpaw leaf','Molted feather envelope','Unidentified acorn cap','Old antler shed record','Dried mud sample']},
{title:'Surveys & maps',ids:[],text:'New trail surveys and places will add more papers to this pile.',notes:['The hollow oak','South slope trail extension','A spring not yet mapped','An illegible nighttime field entry','Creek-crossing survey','Unmarked survey stake','Ranger’s sealed map']}
];
const done=id=>has('done',id);
const eligible=id=>{const p=piles.find(x=>x.ids.includes(id));if(!p)return false;let n=p.ids.indexOf(id);return p.ids.slice(0,n).every(done)};
const dialog=document.createElement('dialog');dialog.id='fieldCaseDialog';dialog.className='field-case-dialog';dialog.innerHTML='<button class="close-field" aria-label="Close">✕</button><h2></h2><div class="field-case-content"></div>';document.body.append(dialog);
const css=document.createElement('style');css.textContent='.field-case-dialog{box-sizing:border-box;width:min(720px,calc(100vw - 28px));max-height:86dvh;overflow:auto;background:#f1e6cb;color:#2b261a;border:1px solid #9c7d4d;border-radius:12px;padding:24px;box-shadow:0 16px 75px #000b;font:15px/1.55 Arial,sans-serif}.field-case-dialog::backdrop{background:#090b08bd}.field-case-dialog h2{font:27px Georgia,serif;margin:4px 46px 18px 0}.field-case-dialog h3{font:20px Georgia,serif;margin:6px 0}.field-case-dialog article{border-top:1px solid #b9a47c;padding:12px 0}.field-case-dialog p{margin:8px 0 12px}.field-case-dialog small{display:block;color:#6d624c}.field-case-dialog button{border:1px solid #8c704a;background:#304a37;color:#fff;border-radius:7px;padding:9px 14px;min-height:42px;margin:4px 5px 4px 0;cursor:pointer;font:inherit}.field-case-dialog button:disabled{opacity:.55}.field-case-dialog .close-field{float:right;width:44px;color:#281f13;background:transparent;margin:0}.field-case-dialog a{color:#23533a}.ranger-field-find{position:fixed;z-index:25;width:52px;height:52px;transform:translate(-50%,-50%);border:0;background:transparent;touch-action:manipulation;cursor:pointer;visibility:hidden}.ranger-field-find::after{content:"";position:absolute;inset:20px;background:#ae987377;border:1px solid #dfcfad55;border-radius:100%;box-shadow:0 0 10px #c1a57e7d}.ranger-field-find:focus-visible{outline:2px solid #f6dca2}.field-nav{display:flex;flex-wrap:wrap;gap:4px;margin-top:12px}@media(max-width:600px){.field-case-dialog{padding:16px}.field-case-dialog h2{font-size:23px}}';document.head.append(css);
dialog.querySelector('.close-field').onclick=()=>dialog.close();
function show(title,html){dialog.querySelector('h2').textContent=title;dialog.querySelector('.field-case-content').innerHTML=html;if(!dialog.open)dialog.showModal()}
function openStack(i=0){i=Math.max(0,Math.min(6,Number(i)||0));let p=piles[i],html='<p>The ranger keeps these papers in order. The notes underneath rely on what you discover in the ones above.</p>';
if(p.ids.length){p.ids.forEach((id,n)=>{let c=byId[id],unlocked=eligible(id),filed=done(id);html+='<article><small>Paper '+(n+1)+' · '+(filed?'Report filed':unlocked?has('accepted',id)?'In progress':'Ready':'Sealed')+'</small><h3>'+esc(unlocked?c.name:'Unopened report')+'</h3>'+(unlocked?'<p>'+esc(c.intro)+'</p><button data-case="'+id+'">'+(filed?'Read report':'Open report')+'</button>':'<p>Finish the papers above before opening this one.</p>')+'</article>'});html+='<p><strong>Pile complete:</strong> '+(p.ids.every(done)?'Yes — earned your field reward':'Not yet — return with your findings')+'</p>'}else html+='<article><p>'+esc(p.text)+'</p><p>These field papers are waiting for full quests. They are not yet playable.</p></article>'+(p.notes||[]).map((name,k)=>'<article><small>Filed paper '+(k+1)+' · Preview</small><h3>'+esc(name)+'</h3><p>Details are sealed until the corresponding expedition is ready.</p></article>').join('');
html+='<div class="field-nav">'+piles.map((x,j)=>'<button data-pile="'+j+'">Pile '+(j+1)+'</button>').join('')+'</div>';show('Desk pile '+(i+1)+' · '+p.title,html)}
function openCase(id){let c=byId[id];if(!c||!eligible(id))return openStack(0);let n=c.clues.filter(x=>has('clues',x)).length;let html='<p>'+esc(c.intro)+'</p><p><strong>Field observations:</strong> '+n+' / '+c.clues.length+'</p>';
if(n)html+='<p>Found: '+esc(c.clues.filter(x=>has('clues',x)).map(x=>labels[x]).join(' · '))+'</p>';if(id==='bear')html+='<article><small>Ranger’s telephone archive</small><p>Caller described a large dark shape among trees. The ranger referred any claims about Bigfoot to the old Kentucky Live Research Project. A later print examination is more consistent with a bear. This is an in-game fictional case file, not a real sighting.</p></article>';if(n<c.clues.length)html+='<p>Explore the woods and pay attention to what does not belong. The ranger will not put a map pin on every clue.</p>';
if(done(id))html+='<article><h3>Filed report</h3><p>'+esc(c.finish)+'</p><p>Passport stamp: '+esc(c.reward)+'</p></article>';
else if(!has('accepted',id))html+='<button data-accept="'+id+'">Take this assignment</button>';
else html+='<button data-report="'+id+'" '+(n<c.clues.length?'disabled':'')+'>Report back to the ranger</button>';
html+='<p><button data-pile="'+piles.findIndex(p=>p.ids.includes(id))+'">Back to desk pile</button></p>';show(c.name,html)}
function openBoard(){let open=cases.filter(c=>eligible(c.id)&&!done(c.id));show('Project bulletin board','<article><h3>West Virginia Live Research Project</h3><p>We do it live. East Bank and The Roost have dedicated camera destinations. Bird and squirrel clearings are looking for camera sponsors.</p></article><article><h3>Field assignments</h3><p>Completed assignment notices vanish from your own list.</p>'+open.map(c=>'<button data-case="'+c.id+'">'+esc(c.name)+'</button>').join('')+'</article><article><h3>Lost little companion</h3><p>The family left a simple missing poster. No starting clues or directions have been supplied.</p></article>')}
function openLost(){show('Lost & found','<p>The ranger has a few unclaimed things, and no reason to assume everything belongs together.</p><article><h3>Small brass campground bell</h3><p>There is a familiar dent on its edge. Nothing here says why.</p><button data-bell>Inspect the bell</button></article><article><h3>Walking stick handle</h3><p>The initials have nearly worn away.</p></article>')}
function openPassport(){let finished=cases.filter(c=>done(c.id));show('Woodland passport','<p><strong>First visit:</strong> '+new Date(s.firstVisit).toLocaleDateString()+'</p><p><strong>Cases filed:</strong> '+finished.length+'</p><p><strong>Active live viewing on this device:</strong> '+Math.floor(s.watch/60)+' minutes</p><article><h3>Stamps</h3><p>'+(finished.length?finished.map(c=>esc(c.reward)).join(' · '):'Complete field reports to earn stamps.')+'</p></article><small>Your progress is saved in this browser, not your WVLRP account. These stamps do not count as prize drawing entries; drawing rules have not been published.</small>')}
dialog.querySelector('.field-case-content').onclick=e=>{let b=e.target.closest('button');if(!b)return;let d=b.dataset;if(d.pile!==undefined)openStack(d.pile);if(d.case)openCase(d.case);if(d.accept){add('accepted',d.accept);openCase(d.accept)}if(d.report){let c=byId[d.report];if(c&&eligible(c.id)&&c.clues.every(x=>has('clues',x))){add('done',c.id);openCase(c.id)}}if(b.hasAttribute('data-bell')){add('clues','bell');show('A curious coincidence','<p>The old campground inventory shows a bell with a very similar dent. Nothing has been returned yet.</p>')}};
const labels={shells:'Cracked nutshells',wax:'Old honeycomb',shavings:'Whittled branch',tag:'Maintenance tag',toy:'Chewed toy',owl:'Nighttime hoot',daytrail:'Daylight paw marks',print:'Large paw impression',markerfind:'Fallen marker'};
const descriptions={shells:'Pieces of a squirrel’s winter store lie scattered across the leaves. Some shells were split with surprising precision.',wax:'An old crumb of beeswax is caught against the bark. The hive disturbance deserves a closer look.',shavings:'Someone stopped here to whittle a stick. Fresh curls of wood lie beneath the branch.',tag:'A missing maintenance tag lies wedged in the root hollow. The numbering matches an item from the ranger’s inventory.',toy:'A chewed little toy lies half-hidden in the leaves. There is no note saying where to look next.',owl:'A deep hoot rings from the darkness. You record the direction, but there may be nothing to find until daylight.',daytrail:'After a careful return, little paw marks become apparent near the place you heard the owl. The tracks lead away into brush.',print:'The broad paw print looks consistent with a black bear rather than something mysterious.',markerfind:'A wooden trail-marker tag lies where the rain washed it away.'};
function inspect(id){let t=stamp();if(id==='owl'&&(!t.night||!has('clues','toy')))return;if(id==='daytrail'&&(t.night||!s.nightDate||t.date<=s.nightDate))return;
if(id==='daytrail'&&s.daySearch===0){s.daySearch=1;save();show('Searching in daylight','<p>You find a few disturbed leaves, but nothing certain. A more careful look may reveal something.</p>');return}
if(has('clues',id)){show('Field log','<p>That observation has already been entered in your notebook.</p>');return}
add('clues',id);if(id==='owl'){s.nightDate=t.date;save()}show('Field observation · '+labels[id],'<p>'+descriptions[id]+'</p><p>Recorded privately in your field log.</p><p><a href="ranger-station.html">Return to the Ranger Station</a></p>')}
function hotspots(){let page=location.pathname.split('/').pop(),data={
'woodland-trail.html':[['shavings',.60,.72],['toy',.18,.68],['owl',.11,.38],['daytrail',.11,.73]],
'squirrel.html':[['shells',.61,.77]],
'woodland-fork.html':[['wax',.55,.64],['tag',.20,.73],['print',.29,.71],['markerfind',.06,.60]]
}[page]||[];if(!data.length)return;const nodes=data.map(([id,u,v])=>{let b=document.createElement('button');b.type='button';b.className='ranger-field-find';b.setAttribute('aria-label','Inspect something unusual nearby');b.title='Inspect the area';b.onclick=()=>inspect(id);document.body.append(b);return{id,u,v,b}});
const update=()=>{let q=window.WVLRP_QUEST_VIEW?.();if(!q||document.hidden)return;let t=stamp();for(let o of nodes){let available=!has('clues',o.id);if(o.id==='owl')available=available&&t.night&&has('clues','toy');if(o.id==='daytrail')available=available&&!t.night&&!!s.nightDate&&t.date>s.nightDate;o.b.hidden=!available;if(!available)continue;const lat=(.5-o.v)*Math.PI,d=o.u*2*Math.PI-q.yaw,x=Math.cos(lat)*Math.sin(d),wy=Math.sin(lat),z0=Math.cos(lat)*Math.cos(d),y=wy*Math.cos(q.pitch)-z0*Math.sin(q.pitch),z=wy*Math.sin(q.pitch)+z0*Math.cos(q.pitch),f=innerHeight/(2*Math.tan(q.fov/2)),sx=innerWidth/2+f*x/z,sy=innerHeight/2-f*y/z;let visible=z>.25&&sx>20&&sx<innerWidth-20&&sy>35&&sy<innerHeight-20;o.b.style.visibility=visible?'visible':'hidden';if(visible){o.b.style.left=sx+'px';o.b.style.top=sy+'px'}}};update();setInterval(update,250);document.addEventListener('visibilitychange',update)}
function trackWatch(){let v=[...document.querySelectorAll('#eastFeed,#roostFeed,#eastVideo,#roostVideo')];if(!v.length)return;let old=new Map(),then=Date.now();setInterval(()=>{let now=Date.now(),dt=(now-then)/1000;then=now;if(document.hidden||dt>20)return;let played=false;for(let video of v){let a=old.get(video),b=video.currentTime;old.set(video,b);if(!video.paused&&video.readyState>=2&&a!==undefined&&b>a)played=true}if(played){s.watch+=Math.min(10,dt);save()}},10000)}
hotspots();trackWatch();save();window.WVLRP_CASES={openStack,openCase,openBoard,openLost,openPassport,inspect,getProgress:()=>JSON.parse(JSON.stringify(s))};
})();